---
title: "Math571_project"
output: html_document
---

# Getting NYT headlines
```{r}
library(jsonlite)
library(magrittr)
library(tidyverse)
library(lubridate)
library(httr)
library(stringr)
options(max.print=20)

cristobal_key <-  # Insert API key here
year<-1990 #not necessary with the for loop
month<-1 #not necessary with the for loop
ds.used<-character()


for (year in c(1989:1989)){
        #I create the empty data frame for the headlines
        nyt.df<-data.frame()
        for (month in c(1:12)){
        
                url.nyt.archive<-paste0("https://api.nytimes.com/svc/archive/v1/",year,"/"  
                                        ,month,".json","?api-key=",cristobal_key)
                df.json<-fromJSON(url.nyt.archive)
                
                #I extract the headlines from the json file
                #headlines<-df.json$response$docs$headline #use this until 2005
                
                #The structure of df.json$response$docs$headline changes in 1995-03 
                #(a new column appears)so we need the following line to make it consistent
                #Until 2005 use the following lines
                headlines<-df.json$response$docs$headline[1:2]

                
                #As of 2006 the structure of the data follows an irregular pattern
                #some months the headlines are presented as data frame
                #and other months as nested lists. So we need the following conditional
                #structure to deal with different data types
                head.class<-class(headlines)
                if (head.class=="data.frame"){
                section<-df.json$response$docs$section_name
                date.pub<-ymd_hms(df.json$response$docs$pub_date)
                }
                

                if (head.class=="list"){
                list.processed<-sapply(df.json$response$docs$headline,
                                       function(l) c(l$main,l$kicker)[1:2])
                headlines<-plyr::ldply(list.processed, rbind)
                dims<-sapply(list.processed,FUN = length)
                missing.headlines<-which(dims!=2)
                section<-df.json$response$docs$section_name[-missing.headlines]
                date.pub<-ymd_hms(df.json$response$docs$pub_date)[-missing.headlines]
                }
                
                #I want to keep track of the data structures used
                ds.used<-c(ds.used,paste0(year,"-",month," ",head.class))
                
                #I extract the date and section name and add it to the data frame
                
                headlines<-cbind(headlines,section, date.pub)
                
                colnames(headlines)<-c("main","kicker","section_name","pub_date")
                #the following 2 lines are to store the section and date as character
                #in de data frame instead as a factor
                headlines$section_name<-as.character(headlines$section_name)
                headlines$pub_date<-as.character(headlines$pub_date)
                nyt.df<-rbind(nyt.df,headlines)
                print(c(year,month,head.class,length(headlines$pub_date)))
        }
        #I identify the headlines from the "Business" category
        bus.indexes<-str_detect(nyt.df$section_name, "Business")
        bus.indexes[is.na(bus.indexes)]<-F
        #I create a subset of the data frame with only the business headlines
        nyt.df.bus<-nyt.df[bus.indexes,]
        
        write.csv(nyt.df,paste0("data/nyt_headlines_",year,".csv"))
        write.csv(nyt.df.bus,paste0("data/nyt_headlines_bus_",year,".csv"))
        

        
}

```

```{r}
#This chunk is just to check how many API requests I have left
url.get<-paste0("https://api.nytimes.com/svc/archive/v1/",year,"/",month,".json","?api-key=",cristobal_key)
get.json<-GET(url.get)
get.json$headers[24:27]

```
```{r}
#testing chunk
library(curl)
myURL<-function(year,month){

url.nyt.archive<-paste0("https://api.nytimes.com/svc/archive/v1/",year,"/"  
                                        ,month,".json","?api-key=",cristobal_key)
return(url.nyt.archive)
}

url.nyt.archive<-myURL(2007,1)
df.json1<-fromJSON(url.nyt.archive,flatten = T)
#str(df.json$response$docs$headline)

url.nyt.archive<-myURL(2007,11)
df.json2<-fromJSON(url.nyt.archive)

class(df.json1$response$docs$headline)
class(df.json2$response$docs$headline)
```


```{r}
#testing chunk
table(nyt.df.bus$pub_date)
df.json$response$docs$headline$main[1]
df.json$response$docs$headline[1,]
head(df.json$response$docs$headline)
as.data.frame(unlist(df.json$response$docs$headline))
head(plyr::ldply(df.json$response$docs$headline, rbind))
str(df.json$response$docs$headline)

list.processed<-sapply(df.json$response$docs$headline,function(l) c(l$main,l$kicker)[1:2])
plyr::ldply(list.processed, rbind)
dims<-sapply(list.processed,FUN = length)
list.processed[which(dims!=2)]
df.json$response$docs$headline[which(dims!=2)]
df.json$response$docs$headline[1]
as.data.frame(list.processed)
section<-df.json$response$docs$section_name
section[1232]
df.json$response$docs$headline[1232]
df.json$response$docs$headline[1:3]
```
