---
title: "test_comparison"
author: "Cristobal Sarome"
date: "March 26, 2018"
output: html_document
---
```{r}
library(jsonlite)
library(magrittr)
library(tidyverse)
library(lubridate)
library(httr)
library(stringr)
options(max.print=100)
Connor_key <- "5b15a6f528e7486cbd51dd2f47265d25"
nyt.API.key <-"5b4e1b897deb448caa65b58d6c5941ab"  # Insert API key here
nyt.API.key<- Connor_key
year<-1990 #not necessary with the for loop
month<-1 #not necessary with the for loop
ds.used<-character()
```

```{r}

for (year in c(2010:2010)){
        #I create the empty data frame for the headlines
        nyt.df<-data.frame()
        for (month in c(3:3)){
        
                url.nyt.archive<-paste0("https://api.nytimes.com/svc/archive/v1/",year,"/"  
                                        ,month,".json","?api-key=",nyt.API.key)
                df.json<-fromJSON(url.nyt.archive)
                
                #I extract the headlines from the json file
                #headlines<-df.json$response$docs$headline #use this until 2005
                
                #The structure of df.json$response$docs$headline changes in 1995-03 
                #(a new column appears)so we need the following line to make it consistent
                #Until 2005 use the following lines
                headlines<-df.json$response$docs$headline[1:2]
                
                
                #As of 2006 the structure of the data follows an irregular pattern
                #some months the headlines are presented as data frame
                #and other months as nested lists. So we need the following conditional
                #structure to deal with different data types
                head.class<-class(headlines)
                if (head.class=="data.frame"){
                section<-df.json$response$docs$section_name
                news.desk<-df.json$response$docs$news_desk
                date.pub<-ymd_hms(df.json$response$docs$pub_date)
                }
                

                if (head.class=="list"){
                list.processed<-sapply(df.json$response$docs$headline,
                                       function(l) c(l$main,l$kicker)[1:2])
                headlines<-plyr::ldply(list.processed, rbind)
                dims<-sapply(list.processed,FUN = length)
                missing.headlines<-which(dims!=2)
                section<-df.json$response$docs$section_name[-missing.headlines]
                date.pub<-ymd_hms(df.json$response$docs$pub_date)[-missing.headlines]
                news.desk<-df.json$response$docs$news_desk[-missing.headlines]
                }
                
                #I want to keep track of the data structures used
                ds.used<-c(ds.used,paste0(year,"-",month," ",head.class))
                
                #I extract the date and section name and add it to the data frame
                
                headlines<-cbind(headlines,section, date.pub,news.desk)
                
                colnames(headlines)<-c("main","kicker","section_name","pub_date","news_desks")
                #the following 2 lines are to store the section and date as character
                #in de data frame instead as a factor
                headlines$section_name<-as.character(headlines$section_name)
                headlines$pub_date<-substr(as.character(headlines$pub_date),1,10)
                nyt.df<-rbind(nyt.df,headlines)
                print(c(year,month,head.class,length(headlines$pub_date)))
        }
        #I identify the headlines from the "Business" category
        bus.indexes1<-str_detect(tolower(nyt.df$section_name), "business")
        bus.indexes1[is.na(bus.indexes1)]<-F
        bus.indexes2<-str_detect(tolower(nyt.df$news_desk), "(business|financial)")
        bus.indexes2[is.na(bus.indexes2)]<-F
        bus.indexes3<-str_detect(tolower(nyt.df$kicker), "(business|financial)")
        bus.indexes3[is.na(bus.indexes3)]<-F
        bus.indexes<-bus.indexes1 | bus.indexes2 | bus.indexes3
        #I create a subset of the data frame with only the business headlines
        nyt.df.bus<-nyt.df[bus.indexes,]
        
        write.csv(nyt.df,paste0("nyt_headlines_",year,".csv"))
        write.csv(nyt.df.bus,paste0("nyt_headlines_bus_",year,".csv"))
}
mail.nyt.arch<-nyt.df[c(1,4)]
mail.nyt.arch<-mail.nyt.arch[str_detect(mail.nyt.arch$pub_date,"2010-03-0(5|6|7)"),]
rownames(mail.nyt.arch)<-c()
colnames(mail.nyt.arch)<-c("headline","date_pub")

write.csv(mail.nyt.arch[[1]],"2010-03-0567-archive.csv")

```

```{r}
mail.nyt.art<-data.frame()
temp_begin_date<- ymd("20100305")
temp_end_date<- ymd("20100307")
page<-0
 
for (page in c(0:10000)){
        art.temp <- fromJSON(
                paste0("http://api.nytimes.com/svc/search/v2/articlesearch.json?begin_date=",
        temp_begin_date,"&end_date=",temp_end_date,"&api-key=",nyt.API.key,"&page=",page))
        temp.headlines<-data.frame(headline=art.temp$response$docs$headline$main[1:10],
                date_pub=substr(art.temp$response$docs$pub_date[1:10],1,10), stringsAsFactors = F
        )
        mail.nyt.art<-rbind(mail.nyt.art,temp.headlines)
        if ((page*10>art.temp$response$meta$hits)) break
        
        print(c(page,art.temp$response$meta$hits,length(mail.nyt.art[[1]]) ))
        
        Sys.sleep(1.2)
        
}
write.csv(mail.nyt.art,"2010-03-0567_search_article.csv")

dim(art.temp$response$docs)
art.temp$response$docs$new_desk
art.temp$response$meta$hits
art.temp$response$docs$headline$main[1:50]
head.proc<-toupper(mail.nyt.art)
str_replace_all(head.proc[1:10], "(?!\\w| ).", "")
```
```{r}
# mail.nyt.art<-read.csv("old2010-03-0567_search_article.csv",stringsAsFactors = F)
# mail.nyt.art<-mail.nyt.art[2]
# mail.nyt.art<-mail.nyt.art[!is.na(mail.nyt.art[[1]]),]
# write.csv(mail.nyt.art,"2010-03-0567_search_article.csv")
archive.chr<-mail.nyt.arch
archive.chr$headline<-toupper(archive.chr$headline)
archive.chr$headline<-str_replace_all(archive.chr$headline, "(?!\\w| ).", "")

article.chr<-mail.nyt.art
article.chr$headline<-toupper(article.chr$headline)
article.chr$headline<-str_replace_all(article.chr$headline, "(?!\\w| ).", "")

len.comp<-max(c(length(archive.chr),length(article.chr)))

sum(duplicated(article.chr))
sum(duplicated(archive.chr))


sum(duplicated(article.chr$headline))
sum(duplicated(archive.chr$headline))
# archive.chr<-unique(archive.chr)
# article.chr<-unique(article.chr)
dup.index<-duplicated(archive.chr$headline)
archive.chr<-archive.chr[!dup.index,]

dup.index<-duplicated(article.chr$headline)
article.chr<-article.chr[!dup.index,]
names(archive.chr)
equals<-merge(archive.chr,article.chr,by="headline",all = T)
write.csv(equals,"comparison_analysis.csv")

# tests
# archive.chr[str_detect(archive.chr$headline,"OBAMA WIELDS"),][[1]]
equals<-merge(X,Y,all = T)

len.comp<-max(c(length(archive.chr),length(article.chr)))
comparison<-data.frame(cbind(archive.chr[1:len.comp],article.chr))
colnames(comparison)<-c("ARCHIVE","ARTICLE")
write.csv(comparison,"comparison.csv")

X<-archive.chr
X<-as.data.frame(X)
colnames(X)<-"HEADLINES"
X$ARCHIVE<-"YES"
Y<-article.chr
Y<-as.data.frame(Y)
colnames(Y)<-"HEADLINES"
Y$ARTICLE<-"YES"
equals<-merge(X,Y,all = T)


```
```{r}
#This chunk is just to check how many API requests I have left
url.get<-paste0("https://api.nytimes.com/svc/archive/v1/",year,"/",month,".json","?api-key=",nyt.API.key)
url.get2<-paste0("http://api.nytimes.com/svc/search/v2/articlesearch.json?begin_date=",
        "20100305","&end_date=","20100306","&api-key=",nyt.API.key,"&page=0")
get.json1<-GET(url.get)
get.json2<-GET(url.get2)
get.json1$headers[24:27]
get.json2$headers[7:10]
rm(get.json1,get.json2,url.get,url.get2)
```
