---
title: "Stock_Price_Headlines_Naive_Bayes"
author: "Cristobal Sarome"
date: "April 15, 2018"
output: html_document
---
Reference:https://rpubs.com/cen0te/naivebayes-sentimentpolarity

```{r}
# Load required libraries
library(tm)
library(RTextTools)
library(e1071)
library(dplyr)
library(caret)
#library("xlsx")
library(stringr)
# Library for parallel processing
# library(doMC)
# registerDoMC(cores=detectCores())  # Use all available cores
```

```{r}
#Loading data
file.dir<-"../data/Complete Data/nyt_headlines_combined.csv"
headlines.df<-read.csv(file.dir,stringsAsFactors = F)
date_format_different<-which(str_detect(headlines.df[[1]],"/"))
month<-headlines.df[date_format_different,1]%>%
      str_extract("\\d+(?=/)")%>%
      str_pad(2,pad=0)
day<-headlines.df[date_format_different,1]%>%
      str_extract("(?<=/)\\d+(?=/)")%>%
      str_pad(2,pad=0)
year<-str_extract(headlines.df[date_format_different,1],"(?<=/)\\d+$")
headlines.df[date_format_different,1]<-paste0(year,"-",month,"-",day)
headlines.df[1]<-substr(headlines.df[[1]],1,10)
file.dir.clean<-"../data/Complete Data/nyt_headlines_combined_clean.csv"
write.csv(headlines.df,file.dir.clean)
```

