---
title: "Stock_Price_Headlines_Naive_Bayes"
author: "Cristobal Sarome"
date: "April 15, 2018"
output: html_document
---
References:
https://rpubs.com/cen0te/naivebayes-sentimentpolarity
http://kenbenoit.net/pdfs/text_analysis_in_R.pdf



```{r}
# Load required libraries
library(tm)
library(RTextTools)
library(e1071)
library(dplyr)
library(caret)
library("xlsx")
library(stringr)
library(tidytext)
library(quanteda)
# Library for parallel processing
# library(doMC)
# registerDoMC(cores=detectCores())  # Use all available cores
options(max.print=100)
```

```{r}
#Loading data
headlines.dir<-"../data/Complete Data/nyt_headlines_combined_clean.csv"
headlines.df<-read.csv(headlines.dir,stringsAsFactors = F)
headlines.df[str_detect(headlines.df[[1]],"/"),]
stocks.dir<-"../data/Complete Data/FullDJIA.xlsx"
stocks.df<-read.xlsx(stocks.dir,1)
names(headlines.df)[2]<-"date"
names(stocks.df)[1]<-"date"
combined.df<-merge(headlines.df,stocks.df,by="date",all.x = TRUE)
sapply(combined.df,function(x) sum(is.na(x)))
combined.df<-combined.df[-c(2,28:33)]
Nrows<-dim(combined.df)[1]
adapted.df<-cbind(combined.df[4:Nrows,c(1,27)],combined.df[1:(Nrows-3),2:26],
                  combined.df[2:(Nrows-2),2:26],combined.df[3:(Nrows-1),2:26])
adapted.df<-adapted.df[!is.na(adapted.df[[2]]),]
#In order to process the headlines with the Naive Bayes Classifier, we combine all the headlines from 3 days previous to the prediction in a single doccument
adapted.df<-cbind(adapted.df[1:2], apply(adapted.df[,3:77],1,paste, collapse=" "),stringsAsFactors=F)
names(adapted.df)<-c("date","price_change","text")
```

```{r}
#To process the text with the NLP tools from the package tm we have to create a corpus
corpus <- Corpus(VectorSource(adapted.df$text))
corpus.clean <- corpus %>%
  tm_map(content_transformer(tolower)) %>% 
  tm_map(removePunctuation) %>%
  tm_map(removeNumbers) %>%
  tm_map(removeWords, stopwords(kind="en")) %>%
  tm_map(stripWhitespace)
as.character(corpus.clean[[1]])

corpus.headlines<-corpus(corpus.clean)

#Now we create the Document Term Matrix to use for Naive Bayes
headlines.dtm <- DocumentTermMatrix(corpus.clean)
headlines.dtm
#we are interested in the words that appear at least 5 times in the corpus
headlines.freq.words <- findFreqTerms(headlines.dtm, 5)
headlines.dtm[, headlines.freq.words]
#we divide the DTM and the labels vector in train and test set
dtm.train<-headlines.dtm[1:300,]
dtm.test<-headlines.dtm[301:400,]
labels.train<-adapted.df[1:300,2]
labels.test<-adapted.df[301:400,2]
#For this implementation of the Naive Bayes algorithm we need
#to convert the frequency matrix in a yes/no matrix. Where yes
#means that the word is present in that document and no that it's not.
# dummy<-tidy(headlines.dtm[1:5,1:5])
# dtm.matrix.train<-as.matrix.csr(dtm.train)
# dtm.matrix.test<-as.matrix.csr(dtm.test)
convert_counts <- function(x) {
x <- ifelse(x > 0, "Yes", "No")
}

# MARGIN = 1 is used for rows and 2 for columns
headlines.train <- apply(dtm.train, MARGIN = 2, convert_counts)
headlines.test <- apply(dtm.test, MARGIN = 2, convert_counts)
```

```{r}
healines.classifier <- naiveBayes(headlines.train,labels.train)
headlines.predict<-predict(healines.classifier,headlines.test)
```
```{r}
dfm(corpus.headlines)
```

